#include "gdpPhysics/interfaces/cRigidBodyDesc.h"
#include "gdpPhysics/interfaces/eShapeType.h"
#include "gdpPhysics/interfaces/iPhysicsFactory.h"
#include "gdpPhysics/interfaces/iPhysicsWorld.h"
#include "gdpPhysics/interfaces/iRigidBody.h"
#include "gdpPhysics/interfaces/iShape.h"
#include "gdpPhysics/interfaces/shapes.h"